# Generated by Django 5.1.1 on 2024-09-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('dirrecion', models.CharField(max_length=100)),
            ],
        ),
    ]
